# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-23 12:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit3', '0002_samplestatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Replicatect',
            fields=[
                ('replicatectid', models.AutoField(primary_key=True, serialize=False)),
                ('replicatect', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'replicatect',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Standardcurve',
            fields=[
                ('standardcurveid', models.AutoField(primary_key=True, serialize=False)),
                ('standardcurvedescription', models.CharField(blank=True, max_length=45, null=True)),
                ('point1', models.FloatField(blank=True, null=True)),
                ('point2', models.FloatField(blank=True, null=True)),
                ('point3', models.FloatField(blank=True, null=True)),
                ('point4', models.FloatField(blank=True, null=True)),
                ('point5', models.FloatField(blank=True, null=True)),
                ('point6', models.FloatField(blank=True, null=True)),
                ('point7', models.FloatField(blank=True, null=True)),
                ('point8', models.FloatField(blank=True, null=True)),
                ('point9', models.FloatField(blank=True, null=True)),
                ('point10', models.FloatField(blank=True, null=True)),
                ('point11', models.FloatField(blank=True, null=True)),
                ('point12', models.FloatField(blank=True, null=True)),
                ('point13', models.FloatField(blank=True, null=True)),
                ('point14', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'standardcurve',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Standardcurvecriteria',
            fields=[
                ('standardcurvecriteriaid', models.AutoField(primary_key=True, serialize=False)),
                ('slope', models.FloatField(blank=True, null=True)),
                ('correlation', models.FloatField(blank=True, null=True)),
                ('intercept', models.FloatField(blank=True, null=True)),
                ('baseline3', models.FloatField(blank=True, null=True)),
                ('posdeltact', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'standardcurvecriteria',
                'managed': False,
            },
        ),
    ]
