# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit3', '0003_replicatect_standardcurve_standardcurvecriteria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plateqcresult',
            fields=[
                ('idplateqcresult', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'plateqcresult',
                'managed': False,
            },
        ),
    ]
